### ISSUE TITLE
Manual subscripts

### ISSUE THREAD

**Issue by brucetesar** [int2str/jssyntaxtree#1]
In the old php version, it was possible to add manual subscripts to nodes using the underscore notation: "N_i" came out as N with subscript i. This feature doesn't work for me in the new js version. Has it not been implemented (yet)?

P.S. Thanks for maintaining this very useful tool.

**Comment by int2str** [comment]
Thank you so much for your bug report!
Yes, that feature was not ported over initially. Since it's not documented well, I wasn't sure anyone was actually using it. Your bug report was all that's needed to convince me it's useful.

I've added the feature back into the new version (1.02) which is live now.
We'll also try to document it better so others can discover that feature.

Thanks again for the bug report and let us know please if you find any other issues or have any feature request(s).

Thanks!

**Comment by brucetesar** [comment]
Thanks for the update; that was fast!
I've tried it out, and I notice that it works well for non-leaf nodes. However, I couldn't get it to work for leaf nodes. For instance, if I have a trace as a leaf node, and I try to co-index it, I still get t_i in the result. Could you extend the pattern to leaf nodes?

**Comment by int2str** [comment]
I filed issue #2 for this and uploaded a fix for it.
Not perfect at this point, but hopefully good enough for your purposes.

Thanks again for your feedback! Much appreciated!
